# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: product-applicationset
#   namespace: argocd
# spec:
#   generators:
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 - name: dev
#                   namespace: dev
#                 - name: alpha
#                   namespace: stage
#                 - name: prod
#                   namespace: prod
#           - list:
#               elements:
#                 - chart: core
#                   chartPath: charts/core
#                   valuesFile: ../../environments/{{name}}/core-values.yaml
#                 - chart: spaces
#                   chartPath: charts/spaces
#                   valuesFile: ../../environments/{{name}}/spaces-values.yaml
#   template:
#     metadata:
#       name: '{{chart}}-{{name}}'
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/galregev-ops/gitops-example-repo
#         targetRevision: main
#         path: '{{chartPath}}'
#         helm:
#           valueFiles:
#             - '{{valuesFile}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: '{{namespace}}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         syncOptions:
#         - CreateNamespace=true