apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/galregev-ops/gitops-example-repo.git
        revision: main
        directories:
        - path: microservices/*/values/*
  template:
    metadata:
      name: "{{path[0]}}-{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/galregev-ops/gitops-example-repo.git
        targetRevision: main
        path: "microservices/{{path[0]}}"
        helm:
          valueFiles:
            - "microservices/{{path[0]}}/values/{{path[1]}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
