apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.8.2
      helm:
        valueFiles:
          - $gitops_repo/charts/argocd/values.yaml
    - repoURL: https://github.com/galregev-ops/gitops-example-repo.git
      targetRevision: main
      ref: gitops_repo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
